services:
  - type: web
    name: mexc-volume-bot
    env: python
    region: frankfurt  # или singapore для Азии
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python MexcBot.py
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: alerts-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1


